export const SWIGGY_URL = 'https://www.swiggy.com/dapi/restaurants/list/v5?lat=28.549642&lng=77.1211905&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING';
export const RESTAURANT_URL = 'restaurants';
export const ERROR_MSG = 'oops!! something went wrong.';
export const COPYRIGHT = 'Copyright @2024';
export const GROCERY = "Welcome to the grocery store and It will be available soon !!";
export const IMAGELINK = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/";
export const CARDTYPE = "type.googleapis.com/swiggy.presentation.food.v2.ItemCategory";
export const GITHUB_URL = "https://api.github.com/users/Amrinder-27";
export const REGULAR_MENU = "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=28.549642&lng=77.1211905&restaurantId=";
export const REGULAR_MENU_ID = "&catalog_qa=undefined&isMenuUx4=true&submi";